kino/urls.py
from django.urls import path
from kino import views

app_name = 'kino'

urlpatterns = [
    path('film/', views.main_page, name='film'),
    path('film/<int:id>', views.single_film, name='film'),
    path('review/<int:id>', views.review, name='review'),
    path('video/<int:pk>/', views.video, name='video'),
    path('genre/', views.genres, name='genre'),
    path('genre/<int:id>/', views.single_genre, name='genre'),
    path('genre/<int:id>/page-<int:page>/', views.single_genre, name='genre'),
    path('person/<int:id>', views.single_person, name='person'),
    path('vote/', views.vote, name='vote'),
    path('set-review-rating/', views.set_review_rating, name='set_review_rating')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from kino.views import main_page

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', main_page, name='index'),
    path('page/<int:page>/', main_page, name="index-page"),
    path('', include('kino.urls', namespace='kino')),
    path('users/', include('users.urls', namespace='users')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import user_login, registration, logout_user, profile

app_name = 'users'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('registration/', registration, name='registration'),
    path('logout/', logout_user, name='logout'),
    path('profile/', profile, name='profile'),
]

templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ page_title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/index-page.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.svg' %}"/>
    <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src={% static "js/main.js" %}></script>
  </head>
  <body>
    <header class="header">
      <div class="container">
        <a href="{% url 'index' %}" class="logo">Кинопоиск</a>
        <form method="get" action="{% url 'index' %}">
          <input type="text" name="search" id="search" placeholder="Поиск...">
        </form>
        <div class="user">
          {% if user.is_authenticated %}
            <div class="user_profile p1">
              <a class="user_link" href="{% url 'users:profile' %}">{{ user.username }}</a>
              <div class="submenu">
                {% if user.is_staff %}
                <a href="{% url 'admin:index' %}" target="_blank">Админ панель</a>
                {% endif %}
                <a href="{% url 'users:logout' %}">Выйти</a>
              </div>
            </div>
          {% else %}
            <a href="{% url 'users:login' %}" class="user_auth p1">Войти</a>
          {% endif %}
        </div>
      </div>
    </header>
    {% block main %}

    {% endblock %}
    <footer class="footer">
      <a href="{% url 'index' %}" class="logo">Кинопоиск</a>
    </footer>
  </body>
</html>