kino/urls.py
from django.urls import path
from kino import views

app_name = 'kino'

urlpatterns = [
    path('film/', views.main_page, name='film'),
    path('film/<int:id>', views.single_film, name='film'),
    path('review/<int:id>', views.review, name='review'),
    path('video/<int:pk>/', views.video, name='video'),
    path('genre/', views.genres, name='genre'),
    path('genre/<int:id>/', views.single_genre, name='genre'),
    path('genre/<int:id>/page-<int:page>/', views.single_genre, name='genre'),
    path('person/<int:id>', views.single_person, name='person'),
    path('vote/', views.vote, name='vote'),
    path('set-review-rating/', views.set_review_rating, name='set_review_rating')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from kino.views import main_page

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', main_page, name='index'),
    path('page/<int:page>/', main_page, name="index-page"),
    path('', include('kino.urls', namespace='kino')),
    path('users/', include('users.urls', namespace='users')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kino/models.py
from django.db import models
from users.models import User
from django.core.validators import MaxValueValidator, MinValueValidator, FileExtensionValidator, MinLengthValidator
from django.db.models import Avg


class Genre(models.Model):
    name = models.CharField(max_length=120, null=True, blank=True)
    image = models.ImageField(upload_to='genres_images', null=True, blank=True)

    def __str__(self):
        return self.name
    
    def count_films(self):
        return self.film_set.count()
    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Country(models.Model):
    name = models.CharField(max_length=120, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'


class Year(models.Model):
    year = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return str(self.year)

    class Meta:
        verbose_name = 'Год'
        verbose_name_plural = 'Года'


class Film(models.Model):
    name = models.CharField(max_length=120, null=True, blank=True)
    duration = models.CharField(max_length=20, null=True, blank=True)
    image = models.ImageField(upload_to='films_images', null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True, blank=True)
    genres = models.ManyToManyField(Genre)
    year = models.ForeignKey(Year, on_delete=models.CASCADE, null=True, blank=True)
    trailer = models.FileField(upload_to='trailers', validators=[FileExtensionValidator(allowed_extensions=['mp4'])],
                               null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    budget = models.CharField(max_length=120, null=True, blank=True)
    income = models.CharField(max_length=120, null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name

    def count_film_votes(self):
        return self.ratings.count()

    def get_average_rating(self):
        ratings = self.ratings.all()
        if len(ratings) != 0:
            return round(sum(rating.rating for rating in ratings) / len(ratings), 1)
        else:
            return 0

    def count_reviews(self, type='all'):
        if type == 'all':
            reviews_len = len(Review.objects.filter(film=self.id))
        else:
            reviews_len = len(Review.objects.filter(film=self.id, type=type))
        return reviews_len

    def count_percent_of_reviews(self, type=None):
        percent = self.count_reviews(type) / self.count_reviews() * 100
        return round(percent, 2)
    
    def get_persons_form_film(self):
        persons = {}
        for person in self.personsroles_set.all().exclude(role__name='Актер'):
            if person.role.name not in persons.keys():
                persons[person.role.name] = [person]
            else:
                persons[person.role.name].append(person)
                
        return persons
    
    def get_actors_from_film(self):
        persons = self.personsroles_set.filter(role__name='Актер')
        return persons

    @classmethod
    def get_sorted_films(cls):
        films = cls.objects.all().annotate(average_rating=Avg('ratings__rating')).order_by('-average_rating')
        return films

    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    film = models.ForeignKey(Film, on_delete=models.CASCADE, related_name='ratings')
    rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])

    class Meta:
        unique_together = ('film', 'user')

        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинг'


class Review(models.Model):
    REVIEW_TYPES = (
        ('neutral', 'Нейтральный'),
        ('like', 'Положительный'),
        ('dislike', 'Отрицательный'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)
    text = models.TextField(
        validators=[
            MinLengthValidator(50, )
        ]
    )
    type = models.CharField(choices=REVIEW_TYPES, max_length=30)
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}, {self.film}'

    class Meta:
        unique_together = ('film', 'user')

        verbose_name = 'Рецензия'
        verbose_name_plural = 'Рецензии'

    def count_user_reviews(self):
        return len(self.user.review_set.all())

    def get_positive_reviews(self):
        ratings = self.reviewrating_set.filter(rating='like')
        return len(ratings)

    def get_negative_reviews(self):
        ratings = self.reviewrating_set.filter(rating='dislike')
        return len(ratings)


class ReviewRating(models.Model):
    REVIEW_RATING_TYPES = (
        ('like', 'Положительный'),
        ('dislike', 'Отрицательный'),
    )

    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.CharField(max_length=30, default='like', choices=REVIEW_RATING_TYPES)

    class Meta:
        unique_together = ('review', 'user')

        verbose_name = 'Оценка рецензии'
        verbose_name_plural = 'Оценки рецензии'

    def __str__(self):
        return f'Оценка: {self.review} от {self.user}'


class Role(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Профессия'
        verbose_name_plural = 'Профессии'


class Person(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField(upload_to='persons_images', null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    place_of_birth = models.CharField(max_length=120, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Популярный человек'
        verbose_name_plural = 'Популярные люди'

    def get_roles(self):
        roles = self.personsroles_set.values_list('role__name', flat=True).distinct()
        return list(roles)

    def get_genres(self):
        genres = set()
        for role in self.personsroles_set.all():
            genres.update(role.film.genres.all())
        return list(genres)

    def count_films(self):
        films = []
        for role in self.personsroles_set.all():
            films.append(role.film.id)
        return len(set(films))

    def get_range_of_years(self):
        films = []
        for role in self.personsroles_set.all():
            films.append(role.film.year.year)
        films.sort()
        return f'{films[0]} - {films[-1]}'

    def get_top_films(self):
        films = []
        for role in self.personsroles_set.all():
            films.append(role.film)
        films = list(set(films))
        rated_films = [(film, film.get_average_rating()) for film in films]
        sorted_films = sorted(rated_films, key=lambda x: x[1], reverse=True)
        sorted_films_instances = [film[0] for film in sorted_films]
        return sorted_films_instances[0:5]

    def get_films_by_roles(self):
        roles = self.get_roles()
        res = {}
        for role in roles:
            persons_roles = self.personsroles_set.filter(role__name=role)
            films = [persons_role.film for persons_role in persons_roles]
            res[role] = films
        return res


class PersonsRoles(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Роль человека в фильме'
        verbose_name_plural = 'Роли людей в фильмах'

kino/forms.py
from django import forms
from kino.models import Review, Film, Genre, Year


class FilterForm(forms.ModelForm):
    year = forms.ModelChoiceField(queryset=Year.objects.order_by('-year'))
    genres = forms.ModelChoiceField(queryset=Genre.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['country'].empty_label = 'Все страны'
        self.fields['country'].label = 'Страны'
        self.fields['year'].empty_label = 'Все Годы'
        self.fields['year'].label = 'Годы'
        self.fields['genres'].label = 'Жанры'
        self.fields['genres'].empty_label = 'Все жанры'
        self.fields['country'].required = False
        self.fields['year'].required = False
        self.fields['genres'].required = False

    class Meta:
        model = Film
        fields = ['country', 'genres', 'year']


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['text', 'type', ]
        widgets = {
            'text': forms.Textarea(attrs={
                'class': 'form-input',
                'placeholder': 'Текст'
            }),
        }

kino/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, StreamingHttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator

from kino.models import Genre, Film, Year, Rating, User, Role, Person, Review, ReviewRating
from kino.services import open_file, get_persons_form_film, get_film_review_or_none
from kino.forms import ReviewForm, FilterForm


def main_page(request, page=1):
    films = Film.get_sorted_films()

    search = None
    persons = None
    if request.GET.get('search'):
        search = request.GET.get('search')
        films = films.filter(name__iregex=search)
        persons = Person.objects.filter(name__iregex=search)

    if request.GET.get('genres'):
        films = films.filter(genres=request.GET.get('genres'))

    if request.GET.get('year'):
        films = films.filter(year=request.GET.get('year'))

    if request.GET.get('country'):
        films = films.filter(country=request.GET.get('country'))

    if request.GET.get('sort'):
        sort_method = request.GET.get('sort')
        if sort_method == 'name':
            films = films.order_by('name')
        if sort_method == '-name':
            films = films.order_by('-name')
        if sort_method == '-rate':
            films = films.reverse()
        if sort_method == 'year':
            films = films.order_by('year__year')
        if sort_method == '-year':
            films = films.order_by('-year__year')
        
    if request.GET:
        get_params = ['?']
        for param, value in request.GET.items():
            if len(get_params) == 1:
                get_params.append(f'{param}={value}')
            else:
                get_params.append(f'&{param}={value}')
        get_params = ''.join(get_params)
    else:
        get_params = ''


    paginator = Paginator(films, 4)
    films_on_page = paginator.get_page(page)

    form = FilterForm(request.GET)
    context = {
        'page_title': 'Главная',
        'films': films_on_page,
        'form': form,
        'search': search,
        'persons': persons,
        'get_params': get_params
    }
    return render(request, template_name='kino/pages/films.html', context=context)


def single_film(request, id):
    film = get_object_or_404(Film, id=id)
    page_form = ReviewForm()

    if request.method == "POST":
        form = ReviewForm(data=request.POST)
        if form.is_valid():
            try:
                self_review = Review.objects.get(film_id=id, user_id=request.user.id)
            except ObjectDoesNotExist:
                self_review = Review.objects.create(
                    user=request.user,
                    film_id=id,
                    text=form.cleaned_data['text'],
                    type=form.cleaned_data['type']
                )
                self_review.save()
                return redirect('kino:film', id=id)
        else:
            page_form = form

    self_review = get_film_review_or_none(id, request.user.id)
    reviews = film.review_set.all().exclude(id=self_review.id) if self_review else film.review_set.all()
    context = {
        'film': film,
        'reviews': reviews,
        'user': request.user,
        'form': page_form,
        'self_review': self_review
    }

    return render(request, template_name='kino/pages/single-film.html', context=context)


def review(request, id):
    if request.method.lower() == "delete":
        try:
            review = Review.objects.get(pk=id)
            review.delete()
            return HttpResponse(status=204)
        except:
            return HttpResponse(status=404)


def genres(request):
    genres = Genre.objects.all()
    context = {
        'page__title': 'Жанры',
        'genres': genres
    }
    return render(request, 'kino/pages/genres.html', context=context)


def single_genre(request, id, page=1):
    genre = get_object_or_404(Genre, id=id)
    films = genre.film_set.all()

    paginator = Paginator(films, 5)
    films_on_page = paginator.get_page(page)
    context = {
        'page__title': genre.name,
        'genre': genre,
        'films': films_on_page,
    }
    return render(request, 'kino/pages/single-genre.html', context=context)


def single_person(request, id):
    person = Person.objects.get(id=id)
    context = {
        'person': person
    }
    return render(request, 'kino/pages/single-person.html', context=context)

@csrf_exempt
def vote(response):
    film_id = int(response.POST['film'])
    user_id = int(response.POST['user'])
    new_rating = int(response.POST['rating'])
    try:
        rating = Rating.objects.get(film_id=film_id, user_id=user_id)
        rating.rating = new_rating
        rating.save()
    except ObjectDoesNotExist:
        rating = Rating.objects.create(film_id=film_id, user_id=user_id, rating=new_rating)

    data = {
        'message': 'success'
    }
    return JsonResponse(data)


@csrf_exempt
def set_review_rating(response):
    film_id = int(response.POST['film'])
    user_id = int(response.POST['user'])
    review_id = int(response.POST['review'])
    rating_type = response.POST['type']
    try:
        rating = ReviewRating.objects.get(user_id=user_id, review_id=review_id)
        if rating.rating == rating_type:
            return JsonResponse({
                'status': 'Нет обновлений',
                'no_changed': True,
                'created': False,
            })

        rating.rating = rating_type
        rating.save()

        return JsonResponse({
            'status': 'Успешно обновлено',
            'no_changed': False,
            'created': False,
        })
    except ObjectDoesNotExist:
        rating = ReviewRating.objects.create(review_id=review_id, user_id=user_id, rating=rating_type)
        return JsonResponse({
            'status': 'Успешно создано',
            'no_changed': False,
            'created': True,
        })


def video(request, pk):
    file, status_code, content_length, content_range = open_file(request, pk)
    response = StreamingHttpResponse(file, status=status_code, content_type='video/mp4')

    response['Accept-Ranges'] = 'bytes'
    response['Content-Length'] = str(content_length)
    response['Cache-Control'] = 'no-cache'
    response['Content-Range'] = content_range
    return response

templates/kino/pages/films.html
{% extends 'kino/index.html' %}

{% block content %}
  <div class="films-wrapper">
    {% block sidebar %}
      {% include 'kino/sidebar.html' %}
    {% endblock %}
    {% block films %}
      {% include 'kino/components/films.html' %}
    {% endblock %}
  </div>
{% endblock %}

templates/kino/pages/genres.html
{% extends 'kino/index.html' %}

{% block content %}
  {% if genres %}
    <div class="genres">
      {% for genre in genres %}
        <a href="{% url 'kino:genre' genre.id %}" class="genre">
          {% if genre.image %}
            <img src="{{ genre.image.url }}" alt="" />
          {% endif %}
          <div class="text">
            <div class="h4">{{ genre.name }}</div>
            <div class="p2">Фильмов: {{ genre.count_films }}</div>
          </div>
        </a>
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}

templates/kino/pages/single-film.html
{% extends 'kino/index.html' %}
{% load kino_tags %}

{% block content %}
  <div class="single-film">
    <div class="film__left">
      <div class="film__image">
        <img src="{{ film.image.url }}" alt="" />
      </div>
      {% if film.trailer %}
      <div class="film__trailer">
        <video
          id="my-video"
          class="video-js"
          controls
          preloader="auto"
          width="100%"
          height="200"
          data-setup="{}"  
        >
          <source src="{% url 'kino:video' film.id %}" type="video/mp4">
          <source src="{% url 'kino:video' film.id %}" type="video/webm">

        </video>
        <h4>
          Трейлер
        </h4>
      </div>
      {% endif %}
    </div>
    <div class="film__center">
      <h1 class="film__title">
        {{ film.name }}{% if film.year %}
          ({{ film.year }})
        {% endif %}
      </h1>
      <h2 class="film__subtitle">О фильме</h2>
      <div class="film__about">
        <div class="film__year attr">
          <div class="attr__name">Год производства</div>
          <div class="attr__value">{{ film.year }}</div>
        </div>
        <div class="film__genres attr">
          <div class="attr__name">Жанр</div>
          <div class="attr__value">
            {% for genre in film.genres.all %}
              <a href="{% url 'kino:genre' genre.id %}">{{ genre.name }}</a>
              {% if not forloop.last %}, {% endif %}
            {% endfor %}
          </div>
        </div>
        <div class="film__country attr">
          <div class="attr__name">Страна</div>
          <div class="attr__value">
              <div>{{ film.country.name }}</div> 
          </div>
        </div>
        {% if film.get_persons_form_film %}
          {% for role, persons in film.get_persons_form_film.items %}
          <div class="attr">
            <div class="attr__name">
              {{ role }}
            </div>
            <div class="attr__value">
              {% for person in persons %}
                <a href="{% url 'kino:person' person.person.id %}">
                  {{ person.person }}
                </a>
                {% if not forloop.last %}, {% endif %}
              {% endfor %}
            </div>
          </div>
          {% endfor %}
        {% endif %}
        {% if film.budget %}
        <div class="attr">
          <div class="attr__name">Бюджет</div>
          <div class="attr__value">
              {{ film.budget }}
          </div>
        </div>
        {% endif %}
        {% if film.income %}
        <div class="attr">
          <div class="attr__name">Сборы в мире</div>
          <div class="attr__value">
              {{ film.income }}
          </div>
        </div>
        {% endif %}
        {% if film.release_date %}
        <div class="attr">
          <div class="attr__name">Премьера в мире</div>
          <div class="attr__value">
              {{ film.release_date }}
          </div>
        </div>
        {% endif %}
        {% if film.duration %}
        <div class="attr">
          <div class="attr__name">Время</div>
          <div class="attr__value">
              {{ film.duration }} мин.
          </div>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="film__right">
      <div class="film__rating">
        <div class="votes p3">Оценок: {{ film.count_film_votes }}</div>
        <div class="average h4">Рейтинг: {{ film.get_average_rating }}/10</div>

        <div class="go__vote">
          {% votes user=user film=film %}
        </div>
      </div>
      {% if film.get_actors_from_film %}
        <div class="actors">
          <div class="h4">В главных ролях</div>
          {% for actor in film.get_actors_from_film %}
            <a class="actor" href="{% url 'kino:person' actor.person.id %}">{{ actor.person.name }}</a>
          {% endfor %}
        </div>
      {% endif %}
    </div>
  </div>
  <div class="single-film-descr">
    <div class="h2">
      Описание
    </div>
    <p class="descr">
      {% if film.description %}
      {{ film.description }}
      {% else %}
        Описания нет
      {% endif %}
    </p>
    <div class="go__vote">
      {% votes user=user film=film %}
    </div>
  </div>
    {% if reviews or self_review %}
      <div class="reviews">
        <div class="reviews__left">
          {% if self_review %}
          <div class="self-review">
            <h2>Ваша Рецензия</h2>
            <div class="review {% if self_review.type == 'like' %}positive{% elif  self_review.type == 'dislike' %}negative{% endif %}">
              <div class="review__top">
                <img src="{% if self_review.user.avatar %}{{ self_review.user.avatar.url }}{% else %}https://www.pngall.com/wp-content/uploads/5/User-Profile-PNG-High-Quality-Image.png{% endif %}" alt="" class="avatar">
                <div class="name">
                  <h4>{{ self_review.user.username }}</h4>
                  рецензий: {{ self_review.count_user_reviews }} 
                </div>
                <div class="create_time">
                  {{ self_review.create_time }}
                </div>
                <form id="delete-review-form" method="delete">
                  {% csrf_token %}
                  <button class="delete" data-id="{{ self_review.id }}">
                    удалить
                  </button>
                </form>
              </div>
              <div class="review__content">
                {{ self_review.text }}
              </div>
              {% review_rating user=user review=self_review %}
          </div>
          </div>
          {% endif %}
          {% if reviews %}
            <div class="h2">
              Рецензии зрителей
            </div>
          {% endif %}
          {% for review in reviews %}
          <div class="review {% if review.type == 'like' %}positive{% elif  review.type == 'dislike' %}negative{% endif %}">
            <div class="review__top">
              <img src="{% if review.user.avatar %}{{ review.user.avatar.url }}{% else %}https://www.pngall.com/wp-content/uploads/5/User-Profile-PNG-High-Quality-Image.png{% endif %}" alt="" class="avatar">
              <div class="name">
                <h4>{{ review.user.username }}</h4>
                рецензий: {{ review.count_user_reviews }} 
              </div>
              <div class="create_time">
                {{ review.create_time }}
              </div>
            </div>
            <div class="review__content">
              {{ review.text }}
            </div>
            {% review_rating user=user review=review %}
          </div>
          {% endfor %}
        </div>
        <div class="reviews__right">
          <div class="all p3">
            <span class="h4">
              {% count_review film=film %}
            </span>
            Всего 
          </div>
          <div class="p3">
            <span class="h4 positive">
              {% count_review film=film type='like' %} <span class="percent"> {% count_percent_of_review film=film type='like' %} %  </span>
            </span>
            Хороших
          </div>
          <div class="p3">
            <span class="h4 negative">
              {% count_review film=film type='dislike' %} <span class="percent"> {% count_percent_of_review film=film type='dislike' %} %  </span>
            </span>
            Плохих
          </div>
          <div class="p3">
            <span class="h4 neutral">
              {% count_review film=film type='neutral' %} <span class="percent"> {% count_percent_of_review film=film type='neutral' %} %  </span>
            </span>
            Нейтральных
          </div>
        </div>
      </div>
    {% endif %}

  {% if user.is_authenticated and not self_review %}
  <div class="add-review">
    <form action="{% url 'kino:film' film.id %}" method="POST">
      {% csrf_token %}
      <h2 class="title">
        Написать рецензию
      </h2>
      <div class="error">
        {{ form.type.errors }}
      </div>
      <div class="error">
        {{ form.text.errors }}
      </div>
      <div class="form-inputs">
        {{ form.text }}
        <label class="p1" for="{{ form.type.id_for_label }}">
          Тип отзыва
        </label>
        {{ form.type }}
      </div>
      <button class="btn-y" type="submit">
          Оставить рецензию
      </button>
    </form>
  </div>
  {% endif %}

  {% if not user.is_authenticated and not self_review %}
  <h2>
    Оставлять отзывы могут только авторизованные пользователи
  </h2>
  {% endif %}
{% endblock %}

templates/kino/pages/single-genre.html
{% extends 'kino/index.html' %}
{% load kino_tags %}

{% block content %}
  <div class="single-genre">
    <h1 class="page-title">{{ genre.name }}</h1>

    {% if films %}
      <div class="films">
        {% for film in films %}
          {% film film=film.id %}
        {% endfor %}
      </div>
      {% if films.has_other_pages %}
        <nav class="pagination">
          <ul>
            {% if films.number > 2 %}
              <li>
                <a class="page_number" href="{% url 'kino:genre' id=genre.id page=1 %}">1</a>
              </li>
              <li>...</li>
            {% endif %}
            {% for p in films.paginator.page_range %}
              {% if films.number == p %}
                <li>
                  <span class="page-number">{{ p }}</span>
                </li>
              {% elif p >= films.number|add:'-1' and p <= films.number|add:'1' %}
                <li>
                  <a class="page_number" href="{% url 'kino:genre' id=genre.id page=p %}">{{ p }}</a>
                </li>
              {% endif %}
            {% endfor %}
            {% if films.number != films.paginator.num_pages and films.number != films.paginator.num_pages|add:'-1' %}
              <li>...</li>
              <li>
                <a class="page_number" href="{% url 'kino:genre' id=genre.id page=films.paginator.num_pages %}">{{ films.paginator.num_pages }}</a>
              </li>
            {% endif %}
          </ul>
        </nav>
      {% endif %}
    {% endif %}
  </div>
{% endblock %}

templates/kino/pages/single-person.html
{% extends 'kino/index.html' %}
{% load kino_tags %}

{% block content %}
  <div class="single-person-info">
    <div class="person__left">
      {% if person.image %}
        <img src="{{ person.image.url }}" alt="" />
      {% endif %}
    </div>
    <div class="person__right">
      <div class="h1 title">{{ person.name }}</div>
      <div class="about-person">
        <div class="h2 title">О персоне</div>
        <div class="attr roles">
          <div class="attr__name">Карьера</div>
          <div class="attr__value">
            {% for role in person.get_roles %}
              {{ role }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </div>
        </div>
        {% if person.birthday %}
          <div class="attr birthday">
            <div class="attr__name">Дата рождения</div>
            <div class="attr__value">{{ person.birthday }}</div>
          </div>
        {% endif %}
        {% if person.place_of_birth %}
          <div class="attr place_of_birth">
            <div class="attr__name">Место рождения</div>
            <div class="attr__value">{{ person.place_of_birth }}</div>
          </div>
        {% endif %}
        {% if person.get_genres %}
          <div class="attr genres">
            <div class="attr__name">Жанры</div>
            <div class="attr__value">
              {% for genre in person.get_genres %}
                <a href="#tabs" class="p2">{{ genre.name }}{% if not forloop.last %}, {% endif %}</a>
              {% endfor %}
            </div>
          </div>
        {% endif %}
        <div class="attr films">
          <div class="attr__name">Все фильмы</div>
          <div class="attr__value">
            {{ person.count_films }}, <a href="#tabs" class="p2">{{ person.get_range_of_years }}</a>
          </div>
        </div>
      </div>
      <div class="top-films">
        <h2>Лучшие фильмы</h2>
        <div class="films">
          {% for film in person.get_top_films %}
            <a href="{% url 'kino:film' film.id %}" class="p2">{{ film.name }}</a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="single-person-films">
    <div class="tabs" id="tabs">
      {% for role, films in person.get_films_by_roles.items %}
        <div class="tab {% if forloop.counter == 1 %}active{% endif %}" data-role-tab="{{ forloop.counter }}">
          {{ role }}
          <span>Фильмов: {{ films|length }}</span>
        </div>
      {% endfor %}
    </div>
    <div class="films-blocks">
      {% for role, films in person.get_films_by_roles.items %}
        <div class="film-block {% if forloop.counter == 1 %}active{% endif %}" data-role-block="{{ forloop.counter }}">
          {% for film in films %}
            <a class="film" href="{% url 'kino:film' film.id %}">
              <div class="film__left">
                <div class="h3 name">{{ film }}</div>
                <div class="year">{{ film.year }}</div>
              </div>
              <div class="film__right">
                <div class="votes p3">Оценок: {{ film.count_film_votes }}</div>
                <div class="average h4">Рейтинг: {{ film.get_average_rating }}/10</div>
              </div>
            </a>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/kino/pages/single-year.html
{% extends 'kino/index.html' %}

{% block content %}
    <div class="year">
      {{ year.year }}
    </div>
{% endblock %}