kino/urls.py
from django.urls import path
from kino import views

app_name = 'kino'

urlpatterns = [
    path('film/', views.main_page, name='film'),
    path('film/<int:id>', views.single_film, name='film'),
    path('review/<int:id>', views.review, name='review'),
    path('video/<int:pk>/', views.video, name='video'),
    path('genre/', views.genres, name='genre'),
    path('genre/<int:id>/', views.single_genre, name='genre'),
    path('genre/<int:id>/page-<int:page>/', views.single_genre, name='genre'),
    path('person/<int:id>', views.single_person, name='person'),
    path('vote/', views.vote, name='vote'),
    path('set-review-rating/', views.set_review_rating, name='set_review_rating')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from kino.views import main_page

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', main_page, name='index'),
    path('page/<int:page>/', main_page, name="index-page"),
    path('', include('kino.urls', namespace='kino')),
    path('users/', include('users.urls', namespace='users')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import user_login, registration, logout_user, profile

app_name = 'users'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('registration/', registration, name='registration'),
    path('logout/', logout_user, name='logout'),
    path('profile/', profile, name='profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', null=True, blank=True)

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User
from django import forms


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-input',
        'placeholder': 'Логин'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-input',
        'placeholder': 'Пароль'
    }))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):

    is_admin = forms.BooleanField(required=False)

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-input',
        'placeholder': 'Введите имя пользователя'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-input',
        'placeholder': 'Введите пароль'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-input',
        'placeholder': 'Повторите пароль'
    }))

    class Meta:
        model = User
        fields = ('is_admin', 'username', 'email', 'password1', 'password2')
        
        

class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-input'
    }), required=False)
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-input'
    }), required=False)
    avatar = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'file-input'
    }), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-input',
        'readonly': True
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-input'
    }), required=False)
    
    class Meta:
        model = User
        fields = ('username', 'avatar', 'first_name', 'last_name', 'email')

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, authenticate, logout

from django.contrib.auth.forms import UserCreationForm

from users.models import User
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from django.contrib.auth.models import Group


def user_login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {
        'form': form,
        'page_title': 'Авторизация',
        }
    return render(request, 'users/login.html', context=context)


def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            is_admin = form.cleaned_data.get('is_admin')

            user = authenticate(username=username, password=password)

            if is_admin:
                admin_group = Group.objects.get(name='admin')
                admin_group.user_set.add(user)
                user.is_staff = True
                user.save()

            login(request, user)
            return HttpResponseRedirect(reverse('index'))
    else:
        form = UserRegistrationForm()
    context = {
        'form': form,
        'page_title': 'Регистрация'
    }
    return render(request, 'users/registration.html', context=context)


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def profile(request):
    if request.user.is_authenticated == True:
        if request.method == "POST":
            form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('users:profile'))
        else:
            form = UserProfileForm(instance=request.user)
        context = {
            'page_title': 'Профиль',
            'form' : form,
        }
        return render(request, 'users/profile.html', context=context)
    else:
        return(HttpResponseRedirect(reverse('index')))

templates/users/login.html
{% extends 'main/base.html' %}

{% block main %}
  <main class="users_login">
    <form action="{% url 'users:login' %}" method="post" class="login-form">
      <h1 class="form-title">Войти</h1>
      {% if form.non_field_errors %}
        {{ form.non_field_errors }}
      {% endif %}
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
        {{ form.username }}
      </div>
      <div class="form-group">
        <label for="{{ form.password.id_for_label }}">Пароль</label>
        {{ form.password }}
      </div>
      <button type="submit" class="btn">Отправить</button>
      <div class="register-link">
        Нет аккаунта? <a href="{% url 'users:registration' %}">Зарегистрироваться</a>
      </div>
    </form>
  </main>
{% endblock %}

templates/users/profile.html
{% extends 'main/base.html' %}

{% block main %}
  <main class="users_profile">
    <form class="profile-form" action="{% url 'users:profile' %}" method="POST" enctype="multipart/form-data">
      {% if errors %}
        <div class="errors">
          {% for error in errors %}
            <div class="error">{{ error }}</div>
          {% endfor %}
        </div>
      {% endif %}
      <h1 class="title">
        Пользователь: {{ user.username }}
        <div class="ava">
          {% if user.avatar.url != '' %}
            <img src="{{ user.avatar.url }}" alt="" />
          {% endif %}
        </div>
      </h1>
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ form.first_name.id_for_label }}">Имя</label>
        {{ form.first_name }}
      </div>
      <div class="form-group">
        <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
        {{ form.last_name }}
      </div>
      <div class="form-group avatar">
        <label for="{{ form.avatar.id_for_label }}">Аватарка</label>
        {{ form.avatar }}
      </div>
      <div class="form-group">
        <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
        {{ form.username }}
      </div>
      <div class="form-group">
        <label for="{{ form.email.id_for_label }}">Почта</label>
        {{ form.email }}
      </div>
      <button class="btn" type="submit">Изменить</button>
    </form>
  </main>
{% endblock %}

templates/users/registration.html
{% extends 'main/base.html' %}

{% block main %}
  <main class="users_registration">
    <form action="{% url 'users:registration' %}" method="post" class="registration-form">
      <h1 class="form-title">Зарегистрироваться</h1>
      {% if form.errors %}
        <div class="errors">
          {% if form.username.errors %}
            <div class="error">{{ form.username.errors }}</div>
          {% endif %}
          {% if form.password1.errors %}
            <div class="error">{{ form.password1.errors }}</div>
          {% endif %}
          {% if form.password2.errors %}
            <div class="error">{{ form.password2.errors }}</div>
          {% endif %}
        </div>
      {% endif %}
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
        {{ form.username }}
      </div>
      <div class="form-group">
        <label for="{{ form.password1.id_for_label }}">Пароль</label>
        {{ form.password1 }}
      </div>
      <div class="form-group">
        <label for="{{ form.password2.id_for_label }}">Повторите</label>
        {{ form.password2 }}
      </div>
      <div class="form-group row">
        {{ form.is_admin }}
        <label for="{{ form.is_admin.id_for_label }}">Сделать администратором?</label>
      </div>

      <button type="submit" class="btn">Зарегистрироваться</button>
      <div class="login-link">
        Уже есть аккаунт? <a href="{% url 'users:login' %}">Войти</a>
      </div>
    </form>
  </main>
{% endblock %}